### ISSUE TITLE
compression

### ISSUE THREAD

**Issue by lskatz** [snacktavish/TreeToReads#16]
Would you guys be open to gzipping the output fastq files at the end of the pipeline?  And converting sam to sorted bam, in the interest of compression.

**Comment by tseemann** [comment]
+1 please don't put .SAM files in my filesystem :)

**Comment by lskatz** [comment]
I put in a pull request but please only take it as a suggestion.  I also just took it as an excuse to learn a bit of Python since I'm a beginner.

**Comment by snacktavish** [comment]
Merged! Thanks, I really appreciate it. It does add a dependency on samtools, but I don't think that is a problem because I assume people simulating next gen data usually have it installed already.

**Comment by snacktavish** [comment]
And looks like ART fixed that sam file bug in the newest version.

**Comment by tseemann** [comment]
Yes I think having `samtools` is a very safe bet!
