### ISSUE TITLE
Don't force /usr/bin/python

### ISSUE THREAD

**Issue by tseemann** [snacktavish/TreeToReads#17]
Please use `#!/usr/bin/env python` instead of `#!/usr/bin/python` at the top of your `.py` scripts.

This will ensure you use the default version of python, which is often *not* the system python.

What happens in my case is that it runs, but can't find `dendropy` etc because they aren't in the system location. (I use python from Linuxbrew)

**Comment by snacktavish** [comment]
Ah good point! Fixed.
