### ISSUE TITLE
Just running treetoreads.py did a whole lot of stuff?

### ISSUE THREAD

**Issue by tseemann** [snacktavish/TreeToReads#19]
I went into the `TreeToReads` folder  and ran `treetoreads.py` and suddenly it started doing a lot of stuff and presumably writing files somewhere?

I think it started running automatically because it found a `seqsim.cfg` file in the current directory?

I was expecting to see some command line help etc.

I would recommend not allowing this behaviour and requiring the `cfg` file to be a mandatory parameter.

**Comment by snacktavish** [comment]
Good call. It does automatically run on a default config, but I agree that is confusing and doesn't add much. I'll change that.

**Comment by tseemann** [comment]
Best not to scare the new users :+1:

**Comment by snacktavish** [comment]
Default removed!
