### ISSUE TITLE
Lowercase nucleotides is an issue

### ISSUE THREAD

**Issue by lskatz** [snacktavish/TreeToReads#24]
I discovered that TTR couldn't read my reference genome which was in all lowercase.  Changing it to all uppercase fixed it, but could you modify TTR to be case-insensitive?

**Comment by snacktavish** [comment]
I modified it! It will work with lowercase, but write out all genomes in uppercase, so soft masking will be removed. I don't see any problems with that, but if someone sees one I could use a more nuanced approach, and keep lowercased regions in.
