### ISSUE TITLE
Check 10 recomendations

### ISSUE THREAD

**Issue by snacktavish** [snacktavish/TreeToReads#4]
From http://www.gigasciencejournal.com/content/2/1/15
1. Print something if no parameters are supplied
2. Always have a “-h” or “--help” switch
3. Have a “-v” or “--version” switch
4. Do not use stdout for messages and errors
5. Always raise an error if something goes wrong
6. Validate your parameters
7. Don’t hard-code any paths
8. Don’t pollute the PATH
9. Check that your dependencies are installed
10. Don’t distribute bare JAR files

**Comment by snacktavish** [comment]
1-3. OK
4. Still a problem
5. Close but needs to be checked
6-7. OK
8. Need to check
9. Need to do
10. OK

**Comment by tseemann** [comment]
For 9. I am mainly referring to run-time dependencies, like other binaries/scripts. And even then, it is mainly a courtesy to find out early, before the script half runs *then* dies.

If you are using "pip install treetoreads" then that should cover the python dependencies.

**Comment by snacktavish** [comment]
Ah thanks! It does rely on some other bioinformatics software (seq-gen and ART), and now it will report an error and fail right away if it isn't present. 

I'm still figuring out packaging, but will get that working as well.

**Comment by tseemann** [comment]
* seq-gen is already in Brew: https://github.com/Homebrew/homebrew-science/search?utf8=%E2%9C%93&q=seq-gen

* i have ART now in Brew, just awaiting acceptance: https://github.com/Homebrew/homebrew-science/pull/2368

This should help people install your dependencies.

**Comment by snacktavish** [comment]
Ah perfect, thanks!
