### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by snacktavish** [snacktavish/TreeToReads#5]
GPL?

**Comment by tseemann** [comment]
First, take some headache tablets, then read this:

http://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licenses

**Comment by snacktavish** [comment]
Thanks! I appreciate it. Looks like my options will be somewhat limited by this being a collaboration with the USA FDA, and therefore govt owned, but the article helps.

**Comment by tseemann** [comment]
I'm not sure if you are a PhD student or a postdoc, but In Australia PhD students have copyright over their work.

**Comment by snacktavish** [comment]
Slow response :) I'm a postdoc, but it looks it looks like I should use a standard US govt license, because this project was directly funded by a federal agency. Do you think this text works? https://github.com/snacktavish/TreeToReads/blob/master/LICENSE.txt
